# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73dc182244af30ca91511bf2c59f0c2463d2f1b0224fc0ac4cf9b1912d798314dbe7650fc4f6132ce78ddbbbff463fce9ca2cd936efd6ae8f3d5597d11cc6a22

test:
  secret_key_base: 96c177a01094bc0d17cbbe5df7053593f62b38bf405a37697cd303c16a3a2eea45eaa6dfb1c37eb4f0d197cce3b0abbca73130c0714c35dad2cdf065e950e264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
